# Generated by Django 3.2.5 on 2021-07-21 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0002_alter_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='username',
            new_name='user',
        ),
    ]
